DEFINE TEMP-TABLE ttEntity SERIALIZE-NAME "Entity"
    FIELD cName   AS CHARACTER SERIALIZE-NAME "Name"
    FIELD cFields AS CHARACTER SERIALIZE-NAME "Fields"
    FIELD cFilter AS CHARACTER SERIALIZE-NAME "Filter".
    
    
DEFINE DATASET dsDataset SERIALIZE-NAME "DataDefinition" FOR ttEntity.
